name: "Init @ts-rust monorepo"

description: |
  This action initializes @ts-rust monorepo by installing nodejs,
  pnpm and npm packages and builds the project.

inputs:
  deep-fetch:
    description: "Whether if deep-fetch:0 has to be set during checkout. false by default"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.deep-fetch == 'true'
      with:
        fetch-depth: 0

    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.deep-fetch == 'false'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpm run build
