name: "Init @ts-rust monorepo"

description: |
  This action initializes @ts-rust monorepo by installing nodejs,
  pnpm, npm packages and builds the project.

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpm run build
