name: Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Init
        uses: ./.github/actions/init/action.yml

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

      - name: Test
        run: pnpm run test:cov

  trigger-release:
    needs: [ci-check]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger Release Workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: 'main',
            });
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_PAT }}
