name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init
        uses: ./.github/actions/init

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1.4.10
        with:
          version: pnpm run version
          publish: pnpm run release
          commit: "chore: Version packages"
          title: "Version Packages"
          setupGitUser: true
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
